using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BDapp.classes
{
    public class StockName
    {
        public enum NAME { AIR_LIQUIDE, AIRBUS, ALSTOM, ARCELLORMITTAL, AXA, BNP, BOUYGUES, CARREFOUR ,CAPGEMINI, CREDIT_AGRICOLE, DANONE, DASSAULT_SYSTEMES, ENGIE, ESSILORLUXOTTICA, EUROFINS_SCIENTIFIC, HERMES, KERING, LEGRAND, LOREAL, LVMH, MICHELIN, ORANGE, PERNOD_RICARD, PUBLICIS, RENAULT, SAFRAN, SAINT_GOBAIN, SANOFI, SCHNEIDER, SOCIETE_GENERALE, STELLANTIS, STMICROELECTRONICS, TELEPERFORMANCE, THALES, TOTAL, UNIBAIL, VEOLIA, VINCI, VIVENDI, WORLDLINE};
    }
}
